# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    push_notification.gcm:
        class: AppBundle\Services\GCM
        arguments: [%gcm_token%, %gcm_package_name%]

    push_notification.apn:
        class: AppBundle\Services\APN
        arguments: [%apn_app_id%, %apn_pem_path%, %apn_sandbox%, %apn_pass_phrase%]

    push_notification.ionic:
        class: AppBundle\Services\IonicPush
        arguments: [%ionic_token%, %ionic_profile%]